/********************************************************************
 * Autogenerated file, do not edit.
 *******************************************************************/

#ifndef __GATT_DB_H
#define __GATT_DB_H

#include "bg_gattdb_def.h"

extern const struct bg_gattdb_def bg_gattdb_data;

#define gattdb_service_changed_char           3
#define gattdb_database_hash                  6
#define gattdb_client_support_features        8
#define gattdb_device_name                    11
#define gattdb_board_serial                   20
#define gattdb_board_rev                      22
#define gattdb_firmware_rev                   24
#define gattdb_system_id                      26
#define gattdb_ota_control                    29
#define gattdb_iaq_eco2                       32
#define gattdb_iaq_tvoc                       34
#define gattdb_es_sound_level                 37
#define gattdb_es_pressure                    39
#define gattdb_es_temperature                 41
#define gattdb_es_humidity                    43
#define gattdb_es_uvindex                     45
#define gattdb_es_ambient_light               47
#define gattdb_hall_state                     50
#define gattdb_hall_field_strength            53
#define gattdb_hall_control_point             56
#define gattdb_aio_digital_in                 59
#define gattdb_aio_num_of_digitals_in         62
#define gattdb_aio_digital_out                64
#define gattdb_aio_num_of_digitals_out        66
#define gattdb_ui_rgbleds                     69
#define gattdb_batt_measurement               72
#define gattdb_power_source_type              76
#define gattdb_imu_acceleration               79
#define gattdb_imu_orientation                82
#define gattdb_imu_control_point              85


#endif // __GATT_DB_H
